config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("entry/", include("django_entries.urls")),
    path("", TemplateView.as_view(template_name="home.html")),
]

django_entries/urls.py
from django.urls import path

from .views import (
    add_entry,
    delete_entry,
    edit_entry,
    list_entries,
    scroll_entries,
    view_about,
    view_entry,
)

app_name = "entries"
urlpatterns = [
    path("entries/scroll", scroll_entries, name="scroll_entries"),
    path("entries/list", list_entries, name="list_entries"),
    path("create/add", add_entry, name="add_entry"),
    path("edit/<slug:slug>", edit_entry, name="edit_entry"),
    path("delete/<slug:slug>", delete_entry, name="delete_entry"),
    path("view/<slug:slug>", view_entry, name="view_entry"),
    path("about/", view_about, name="view_about"),
]

django_entries/models.py
import uuid

from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.safestring import mark_safe
from django_extensions.db.fields import AutoSlugField
from django_extensions.db.models import TimeStampedModel

from .utils import convert_md_to_html
from .validators import validate_and_vs_ampersand, validate_capitalized


class Entry(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    slug = AutoSlugField(populate_from=["title", "id"])
    title = models.CharField(
        max_length=50,
        help_text="Title of entry.",
        validators=[validate_capitalized, validate_and_vs_ampersand],
    )
    excerpt = models.CharField(
        max_length=50,
        help_text="Short blurb describing entry displayed in list of entries.",
        validators=[validate_capitalized, validate_and_vs_ampersand],
    )
    content = models.TextField(
        help_text="Markdown text formatting, e.g. ##, *, 1., -, etc."
    )
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="entries"
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "Entry"
        verbose_name_plural = "Entries"

    def __str__(self):
        return f"{self.title} by {self.author}"

    def get_absolute_url(self):
        return reverse("entries:view_entry", kwargs={"slug": self.slug})

    @property
    def md_content(self) -> str:
        return mark_safe(convert_md_to_html(self.content))

    @classmethod
    def get_for_user(cls, slug: str, user):
        """Simple permission checking"""
        entry = get_object_or_404(cls, slug=slug)
        if entry.author != user:
            raise PermissionDenied()
        return entry

django_entries/forms.py
from django import forms
from markdownify import markdownify as md

from .models import Entry


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ("title", "excerpt", "content")

    def clean_content(self):
        """Removed bad tags, e.g. <script>"""
        content = self.cleaned_data["content"]
        cleaned = md(content, strip=["script"])
        return cleaned

django_entries/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, Paginator
from django.db.models import Q
from django.http.request import HttpRequest
from django.http.response import (
    HttpResponse,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from .forms import EntryForm
from .models import Entry

EDITOR = "entries/entry_edit.html"
DETAIL = "entries/entry_detail.html"
FIRST_PAGE = "entries/entry_list.html"
NEXT_PAGE = "entries/entry_next.html"
ITEM_IN_PAGE = "entries/entry_item.html"
MAX_ITEMS_PER_PAGE = 2


@login_required
def edit_entry(
    request: HttpRequest, slug: str
) -> TemplateResponse | HttpResponseRedirect | HttpResponsePermanentRedirect:
    entry = Entry.get_for_user(slug, request.user)
    form = EntryForm(request.POST or None, instance=entry)
    if request.method == "POST":
        if form.is_valid():
            if form.has_changed():
                form.save()
        return redirect(to=entry.get_absolute_url())
    return TemplateResponse(
        request,
        EDITOR,
        {
            "form": form,
            "edit_header": f"Update {entry.title}",
            "mode": "edit",
            "slug": slug,
        },
    )


@login_required
def add_entry(
    request: HttpRequest,
) -> TemplateResponse | HttpResponseRedirect | HttpResponsePermanentRedirect:
    form = EntryForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            entry = form.save(commit=False)
            entry.author = request.user
            entry.save()
            return redirect(to=entry.get_absolute_url())
    return TemplateResponse(
        request, EDITOR, {"form": form, "edit_header": "Write An Entry", "mode": "add"}
    )


@login_required
@require_http_methods(["DELETE"])
def delete_entry(request: HttpRequest, slug: str) -> HttpResponse:
    url = reverse("entries:list_entries")
    entry = Entry.get_for_user(slug, request.user)
    response = HttpResponse(headers={"HX-Redirect": url})
    entry.delete()
    return response


def view_entry(request: HttpRequest, slug: str) -> TemplateResponse:
    return TemplateResponse(
        request, DETAIL, {"entry": get_object_or_404(Entry, slug=slug)}
    )


def set_context(request: HttpRequest, loader: str) -> TemplateResponse:
    """Add to the `url` from the `request` object's `q` and `next`
    parameters, if present.

    Args:
        request (HttpRequest): _description_
        loader (str): _description_

    Returns:
        TemplateResponse: _description_
    """

    # initialize
    context = {}
    context["template_for_item"] = ITEM_IN_PAGE  # template for each page item
    url = reverse("entries:scroll_entries")  # base url for infinity scrolling
    query = request.GET.get("q", None)  # get query from url, else None
    page_number = request.GET.get("next", 1)  # get next from url, else page 1

    # adds to base and filters queryset, if query available; else default
    qs = Entry.objects.all()
    if query:
        url = f"{url}?q={query}"
        qs = qs.filter(
            Q(title__icontains=query)
            | Q(excerpt__icontains=query)
            | Q(content__icontains=query)
        )

    # set page from request
    paginator = Paginator(qs, MAX_ITEMS_PER_PAGE)
    page_obj = paginator.get_page(page_number)
    context["page_obj"] = page_obj

    # adds to base, if next page available
    next_num = None
    if page_obj.has_next:
        try:
            next_num = page_obj.next_page_number()
        except EmptyPage:
            next_num = None
    if next_num:
        context["next_page_url"] = f"{url}?next={next_num}"

    # return html fragment to the template loader
    return TemplateResponse(request, loader, context)


def list_entries(request: HttpRequest) -> TemplateResponse:
    return set_context(request, FIRST_PAGE)


def scroll_entries(request: HttpRequest) -> TemplateResponse:
    return set_context(request, NEXT_PAGE)


def view_about(request: HttpRequest) -> TemplateResponse:
    return TemplateResponse(request, "about.html", {})

django_entries/templates/about.html
{% extends 'base.html' %}
{% block title %} About | BrandX {% endblock title %}
{% block content %}
    <h1>About</h1>
    <main>
        <article>
            <div class="ph4 ph5-m ph6-l">
                <div class="pv5 f4 f2-ns measure center">
                    <p>Sample <mark>text</mark> highlighted for illustration.</p>
                    <blockquote>This is a blockquote<br>- <cite>Quoting from a random person</cite></blockquote>
                    {% lorem 2 p random %}
                </div>
            </div>
        </article>
    </main>
{% endblock content %}

django_entries/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block title %}<title>Test site sample</title> {% endblock title %}<!-- Enable title changes -->
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicons/favicon.ico' %}"/>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
        {% block custom_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/starter.css' %}">
            <link rel="stylesheet" href="https://unpkg.com/pyloncss@latest/css/pylon.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
            {% block extra_css %}
            {% endblock extra_css %}
        {% endblock custom_css %}
    </head>
    <body>
        {% include './base_template/_nav.html' %}
        {% include './base_template/_messages.html' %}
        {% block body %}
            {% block content %}
            {% endblock content %}
            {% block base_js %}
                <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
                <script src="https://unpkg.com/htmx.org@1.6.1"></script>
                <script src="https://unpkg.com/hyperscript.org@0.9.0"></script>
                <script>document.body.addEventListener("htmx:configRequest", (e) => {e.detail.headers["X-CSRFToken"] = "{{ csrf_token }}";});</script>
                {% block extra_js %}
                {% endblock extra_js %}
            {% endblock base_js %}
        {% endblock body %}
    </body>
</html>

django_entries/templates/base_template/_messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

django_entries/templates/base_template/_nav.html
{% url 'entries:view_home' as home_url %}
{% url 'entries:view_about' as about_url %}
{% url 'entries:list_entries' as entries_url %}

<nav>
    <hstack spacing=s align-x=center>
        <a class="button" href="/">BrandX</a>
        <spacer></spacer>
        <a class="button" href="{{about_url}}">About</a>
        <a class="button" href="{{entries_url}}">Blog</a>
    </hstack>
</nav>

django_entries/templates/entries/entry_detail.html
{% extends 'base.html' %}

{% block title %} {{entry.title}} | BrandX {% endblock title %}

{% block content %}
    <hstack spacing=s>
        <h1>{{entry.title}}</h1>
        {% if user.is_authenticated and user == entry.author %}
            <spacer></spacer>
            <button hx-get="{% url 'entries:add_entry' %}" hx-target="body" hx-boost="true">create</button>
            <button hx-get="{% url 'entries:edit_entry' entry.slug %}" hx-target="body" hx-boost="true">edit</button>
            <button hx-delete="{% url 'entries:delete_entry' entry.slug %}" hx-confirm="Are you sure you want to delete?" hx-boost="true">delete</button>
        {% endif %}
    </hstack>
    <hstack>
        <small>By: {{entry.author}}</small>
        <small>, {{ entry.created|date }}</small>
        {% if entry.modified != entry.created %}
            <divider></divider>
            <small>Updated: {{ entry.modified|date }}</small>
        {% endif %}
    </hstack>
    <main>
        <article>{{ entry.md_content}}</article>
    </main>
{% endblock content %}

django_entries/templates/entries/entry_edit.html
{% extends 'base.html' %}

{% block title %}{{edit_header|title}} | BrandX {% endblock title %}

{% block content %}
    <h1>{{edit_header|title}}</h1>
    <main>
      {% if mode == 'add' %}
        {% url 'entries:add_entry' as submit_url %}
      {% elif mode == 'edit' and slug %}
        {% url 'entries:edit_entry' slug as submit_url %}
      {% endif %}
      <form method="post" action="{{submit_url}}">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Submit">
      </form>
    </main>
{% endblock content %}

{% block extra_js %}<script type="text/javascript">var simplemde = new SimpleMDE({forceSync: true});</script>{% endblock extra_js %}

django_entries/templates/entries/entry_item.html
<section>
    <a href="{% url 'entries:view_entry' entry.slug %}" style="text-decoration: none">{{ entry.title }}</a>
    <span style="font-style: italic;">{{entry.excerpt}}</span>
</section>

django_entries/templates/entries/entry_list.html
{% extends 'base.html' %}

{% block title %}<title>Entries | BrandX</title>{% endblock title %}

{% block content %}
    <hstack>
        <h1 stretch>Entries</h1>
        {% if user.is_authenticated %}
            <spacer></spacer>
            <button hx-get="{% url 'entries:add_entry' %}" hx-target="body">Add entry</button>
        {% endif %}
    </hstack>
    <main>
        {% if page_obj %}
            {% include './entry_next.html' %}
        {% else %}
            No entries published yet.
            {% if not user.is_authenticated %}<a href="/admin">Login</a> to add.{% endif %}
        {% endif %}
    </main>
{% endblock content %}

django_entries/templates/entries/entry_next.html
{% for page_item in page_obj %}
    {% if forloop.last and next_page_url %}
        <div hx-get="{{next_page_url}}" hx-trigger="revealed" hx-swap="afterend"></div>
    {% endif %}
    {% include template_for_item with entry=page_item %}
{% endfor %}

django_entries/templates/home.html
{% extends 'base.html' %}

{% block title %} Home | BrandX {% endblock title %}

{% block content %}
    <hstack spacing=s>
        <h1 stretch>Test Site</h1>
        <spacer></spacer>
        <input
            id="autocomplete-search"
            name="q" {% comment %} This is passed as a URL parameter on keyup trigger {% endcomment %}
            type="search"
            placeholder="Search"
            hx-get="{% url 'entries:scroll_entries' %}"
            hx-trigger="keyup changed delay:500ms"
            hx-target="#search-results"
        >
    </hstack>
    <main>
        <section id="search-results">
            {% include 'entries/entry_next.html' with template_for_item='entries/entry_item.html' %}
        </section>
    </main>
{% endblock content %}

entries/templates/_meta.html
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
{% if entry.meta %}
    {{ entry.meta }}
{% else %}
    <meta name="description" content="Sample description "> <!-- # Customize content for search -->
    {% block title %}<title>Test site sample</title> {% endblock title %}<!-- Enable title changes -->
{% endif %}

entries/templates/entry_edit.html
{% extends 'base.html' %}

{% block title %}{{edit_header|title}} | BrandX {% endblock title %}

{% block content %}
    <h1>{{edit_header|title}}</h1>
    <main>{% include '_form.html' %}</main>
{% endblock content %}

{% block extra_js %}<script type="text/javascript">var simplemde = new SimpleMDE({forceSync: true});</script>{% endblock extra_js %}